static const struct arg args[] = {
	/* function 		format          argument */
	{ separator, 		"%s",         	" " },
	{ run_command, 		"%s",        	"~/.local/bin/statusbar/sb-media-nerd" },
	{ run_command, 		"%s",    	"~/.local/bin/statusbar/sb-updates-nerd" },
	{ run_command, 		" %s",      	"~/.local/bin/statusbar/sb-cputemp" },
	{ separator, 		"%s",        	" | " },
	{ run_command, 		"  %s",     	"~/.local/bin/statusbar/sb-down" },
	{ separator, 		"%s",           " | " },
	{ keymap, 		"  %s",         "" },
	{ separator, 		"%s",           " | " },
	{ battery_state, 	"%s ",     	"BAT0" },
	{ battery_perc, 	"  %s",    	"BAT0" },
	{ separator, 		"%s",           " | " },
	{ run_command, 		"  %s",     	"~/.local/bin/statusbar/sb-brightness" },
	{ separator, 		"%s",           " | " },
	{ run_command,		"%s",        	"~/.local/bin/statusbar/sb-sound-nerd" },
	{ separator, 		"%s",           " | " },
	{ wifi_essid, 		"  %s",      	"wlan0" },
	{ separator, 		"%s",           " | " },
	{ datetime, 		"  %s",       	"%a,%d-%m" },
	{ separator, 		"%s",           " | " },
	{ datetime, 		"  %s",      	"%I:%M" },
	{ separator, 		"%s",           " " },
};
